# Generated by Django 5.0.7 on 2024-10-01 09:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_connected', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('device_type', models.CharField(choices=[('lampe', 'Lampe'), ('plug', 'Plug'), ('clima', 'Clima')], default='lampe', max_length=255)),
                ('intensity', models.IntegerField(blank=True, default=0, null=True)),
                ('temperature', models.FloatField(blank=True, default=0, null=True)),
                ('mode', models.CharField(choices=[('auto', 'Auto'), ('cool', 'Cool'), ('dry', 'Dry'), ('heat', 'Heat'), ('fan', 'Fan')], default='auto', max_length=10)),
                ('fan_speed', models.CharField(choices=[('auto', 'Auto'), ('min', 'Min'), ('med', 'Med'), ('max', 'Max')], default='auto', max_length=10)),
                ('turbo', models.BooleanField(default=False)),
                ('swing', models.BooleanField(default=False)),
                ('led', models.BooleanField(default=False)),
                ('sleep', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('salon', 'Salon'), ('cuisine', 'Cuisine'), ('chambre', 'Chambre'), ('salle de bain', 'Salle de bain')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('record_id', models.IntegerField()),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField()),
                ('new_value', models.TextField()),
                ('updated_at', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthome.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='smarthome.room'),
        ),
    ]
