# Generated by Django 5.0.7 on 2024-07-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0004_pageview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageView',
        ),
    ]
