# Generated by Django 5.0.7 on 2024-08-01 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0006_remove_device_connectivity_remove_device_display_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
