# Generated by Django 5.0.7 on 2024-08-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0008_remove_room_created_at_remove_room_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='device',
        ),
        migrations.AddField(
            model_name='sensor',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensors', to='smarthome.room'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('lampe', 'Lampe'), ('plug', 'Plug')], default='Lampe', max_length=255),
        ),
    ]
