# Generated by Django 5.0.7 on 2024-09-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0010_alter_history_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='intensity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
