# Generated by Django 5.0.7 on 2024-09-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0011_device_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='firmware',
        ),
        migrations.RemoveField(
            model_name='device',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('lampe', 'Lampe'), ('plug', 'Plug'), ('clima', 'Clima')], default='Lampe', max_length=255),
        ),
        migrations.DeleteModel(
            name='Sensor',
        ),
    ]
