# Generated by Django 5.0.7 on 2024-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0014_device_temperature_alter_device_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
