# Generated by Django 5.0.7 on 2024-09-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthome', '0015_alter_device_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fan_speed',
            field=models.CharField(choices=[('auto', 'Auto'), ('min', 'Min'), ('med', 'Med'), ('max', 'Max')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='led',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('cool', 'Cool'), ('dry', 'Dry'), ('heat', 'Heat'), ('fan', 'Fan')], default='auto', max_length=10),
        ),
        migrations.AddField(
            model_name='device',
            name='sleep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='swing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='turbo',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
    ]
